CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,

    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    title VARCHAR(120) NOT NULL,

    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_on TIMESTAMP WITHOUT TIME ZONE,

    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,

    state VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    category_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL,

    lat REAL NOT NULL,
    lon REAL NOT NULL,

    CONSTRAINT fk_events_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id),

    CONSTRAINT fk_events_initiator
        FOREIGN KEY (initiator_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_events_participant_limit
        CHECK (participant_limit >= 0),

    CONSTRAINT chk_events_state
        CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,

    CONSTRAINT fk_requests_event
        FOREIGN KEY (event_id)
        REFERENCES events (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_requests_requester
        FOREIGN KEY (requester_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_requests_event_requester
        UNIQUE (event_id, requester_id),

    CONSTRAINT chk_requests_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_compilations_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,

    CONSTRAINT pk_compilation_events
        PRIMARY KEY (compilation_id, event_id),

    CONSTRAINT fk_compilation_events_compilation
        FOREIGN KEY (compilation_id)
        REFERENCES compilations (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_compilation_events_event
        FOREIGN KEY (event_id)
        REFERENCES events (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_events_category_id
    ON events (category_id);

CREATE INDEX IF NOT EXISTS idx_events_initiator_id
    ON events (initiator_id);

CREATE INDEX IF NOT EXISTS idx_events_state_event_date
    ON events (state, event_date);

CREATE INDEX IF NOT EXISTS idx_requests_requester_id
    ON participation_requests (requester_id);

CREATE INDEX IF NOT EXISTS idx_requests_event_status
    ON participation_requests (event_id, status);

CREATE INDEX IF NOT EXISTS idx_compilation_events_event_id
    ON compilation_events (event_id);
